Validate VITE_API_URL before project build
Add check for VITE_API_URL before building the project.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,7 +35,12 @@ jobs:
         run: npm ci
 
       - name: Build project
-        run: npm run build
+        run:     
+          if [ -z "$VITE_API_URL" ]; then
+            echo "::error::VITE_API_URL no está definida"
+            exit 1
+          fi
+          echo "VITE_API_URL está definida"  
         env:
           VITE_API_URL: ${{ vars.VITE_API_URL }}
           VITE_GOOGLE_CLIENT_ID: ${{ vars.VITE_GOOGLE_CLIENT_ID }}
